Repository apache/tvm-rfcs, pull requests merged in 2021-08, with the labels that each got.

#8 Add Project API RFC
  rfcs/0008-microtvm-project-api.md
Labels: status: need review

#14 [RFC] Pipeline Executor
  resources/pipeline-executor-arch.png
  resources/pipeline-executor-pipeline.png
  resources/pipeline-executor-runtime.png
  resources/pipeline-executor-schedule.png
  resources/pipeline-executor-subgraph-split.png
  resources/pipeline-executor.png
  rfcs/0014-pipeline-executor.md
Labels: status: accepted

#6 [RFC] [Relay] Automatic Mixed Precision Pass
  rfcs/0006-AMP_pass.md
Labels: status: accepted

#15 [RFC] Use CMSIS-NN with TVM
  rfcs/0015_Arm_CMSIS-NN_Integration.md
Labels: status: need review

#7 [UnitTests] Parametrized Unit Tests
  rfcs/0007-parametrized-unit-tests.md
Labels: status: need review, status: need update
